# Generated by Django 5.2 on 2025-06-22 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelorder',
            name='employee',
        ),
        migrations.AddField(
            model_name='travelorder',
            name='employees',
            field=models.ManyToManyField(related_name='travel_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
