# Generated by Django 5.2 on 2025-06-22 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0002_remove_travelorder_employee_travelorder_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approving_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
