# Generated by Django 5.2 on 2025-06-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0003_alter_travelorder_current_approver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelorder',
            old_name='departure_date',
            new_name='date_travel_from',
        ),
        migrations.RenameField(
            model_name='travelorder',
            old_name='return_date',
            new_name='date_travel_to',
        ),
        migrations.AddField(
            model_name='travelorder',
            name='evidence',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='fund_cluster',
            field=models.CharField(blank=True, choices=[('01_RF', ')01_RF'), ('07_TF', '07_TF')], max_length=10),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='mode_of_filing',
            field=models.CharField(blank=True, choices=[('IMMEDIATE', 'IMMEDIATE'), ('NOT_IMMEDIATE', 'NOT_IMMEDIATE')], max_length=20),
        ),
        migrations.AddField(
            model_name='travelorder',
            name='number_of_employees',
            field=models.IntegerField(default=0),
        ),
    ]
