# Generated by Django 5.2 on 2025-06-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0004_rename_departure_date_travelorder_date_travel_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='evidence/'),
        ),
    ]
