# Generated by Django 5.2 on 2025-06-25 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0005_alter_travelorder_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='date_of_filing',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 6, 25)),
            preserve_default=False,
        ),
    ]
