# Generated by Django 5.2 on 2025-06-29 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0007_itinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelorder',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_travel_order', to=settings.AUTH_USER_MODEL),
        ),
    ]
