# Generated by Django 5.2 on 2025-06-29 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0008_travelorder_prepared_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_of_fund', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='travelorder',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api1.fund'),
        ),
    ]
