# Generated by Django 5.2 on 2025-06-29 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0009_fund_travelorder_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('means_of_transportation', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='itinerary',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api1.transportation'),
        ),
    ]
