# Generated by Django 5.2 on 2025-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api1', '0010_transportation_itinerary_transportation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('The travel order has been approved by CSC head', 'The travel order has been approved by CSC head'), ('The travel order has been approved by PO head', 'The travel order has been approved by PO head'), ('The travel order has been approved by TMSD chief', 'The travel order has been approved by TMSD chief'), ('The travel order has been approved by AFSD chief', 'The travel order has been approved by AFSD chief'), ('The travel order has been approved by the Regional Director', 'The travel order has been approved by the Regional Director'), ('The travel order has been rejected by CSC head', 'The travel order has been approved by CSC head'), ('The travel order has been rejected by PO head', 'The travel order has been rejected by PO head'), ('The travel order has been rejected by TMSD chief', 'The travel order has been rejected by TMSD chief'), ('The travel order has been rejected by AFSD chief', 'The travel order has been rejected by AFSD chief'), ('The travel order has been rejected by the Regional Director', 'The travel order has been rejected by the Regional Director')], default='Pending', max_length=100),
        ),
    ]
